kind: Deployment
apiVersion: apps/v1
metadata:
  name: country-service
  labels:
    app: country-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: country-service
  template:
    metadata:
      name: country-service
      labels:
        app: country-service
    spec:
      containers:
      - name: country-service
        image: registry.hub.docker.com/andreduursma/country-service
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 2
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 2
          successThreshold: 1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
