kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgresdb
  labels:
    appdb: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: postgresdb
  template:
    metadata:
      labels:
        appdb: postgresdb
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgresdb-config
                  key: database-name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: password
